FROM fncs/zeromq

ENV FNCS_PORT=5570
ENV FNCS_LOG_FILE=yes
ENV FNCS_LOG_STDOUT=yes
ENV FNCS_LOG_TRACE=yes
ENV FNCS_LOG_LEVEL=DEBUG4
ENV FNCS_CONFIG_FILE=""
ENV FNCS_NAME=""
ENV FNCS_BROKER=tcp://*:${FNCS_PORT}
ENV FNCS_LOG_DIR=/fncs/log
ENV FNCS_LOGGING_FILE=${FNCS_LOG_DIR}/fncs.log

RUN mkdir -p ${FNCS_LOG_DIR}
RUN touch ${FNCS_LOGGING_FILE} 

COPY . ${TEMP_DIR}/fncs_src

WORKDIR ${TEMP_DIR}/fncs_src
RUN LD_LIBRARY_PATH=$LD_LIBRARY_PATH:${FNCS_INSTALL}/lib
RUN ./configure --prefix=${FNCS_INSTALL} --with-zmq=${FNCS_INSTALL}
RUN make
RUN make install

WORKDIR /fncs

COPY runit.sh /fncs
RUN chmod +x runit.sh

EXPOSE ${FNCS_PORT}

RUN ls -la
ENTRYPOINT ["./runit.sh"]
